export const USER_LOGIN_SET_EMAIL = 'USER_LOGIN_SET_EMAIL',
	USER_LOGIN_SET_PASSWORD = 'USER_LOGIN_SET_PASSWORD',
	USER_LOGIN_SET_ERROR_MESSAGE = 'USER_LOGIN_SET_ERROR_MESSAGE',
	USER_LOGIN_START_LOADING = 'USER_LOGIN_START_LOADING',
	USER_LOGIN_STOP_LOADING = 'USER_LOGIN_STOP_LOADING',
	USER_LOGIN = 'USER_LOGIN',
	USER_LOGOUT = 'USER_LOGOUT'
